spring:
  banner:
    location: 'classpath:/banner.txt'
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    initialization-mode: always
